[classindex] Properly handle binary class name
bndtools/bnd pull request #4291
Opened 2020-09-03 14:02 UTC by kriegfrj

Fixes #4289.

Signed-off-by: Fr Jeremy Krieg <fr.jkrieg@greekwelfaresa.org.au>

2020-09-03 16:07 UTC, bjhargrave requested changes

2020-09-04 01:06 UTC, kriegfrj commented on biz.aQute.bndlib/src/aQute/bnd/osgi/package-info.java
> +@Version("4.7.0")
There is a minor quirk in the baselining that misled me into making this change - I renamed a method. The newly-named method was requesting a minor version increment. What I didn't notice (at first) was that there was another baseline error at the class level flagging the removal of the old name and requesting a major version increment. I think ideally, in this situation, given that the minor version had already been incremented, the error flagging minor version increment should be suppressed and only the error flagging major version increment should be reported.

2020-09-04 12:57 UTC, bjhargrave approved these changes

2020-09-04 12:57 UTC, merged

2020-09-04 12:57 UTC, bjhargrave commented
Thanks!