[bndtools explorer] Refresh workspace from disk
bndtools/bnd pull request #4510
Opened 2021-01-19 16:45 UTC by pkriens

When the workspace is refreshed from the Bndtools 
explorer, it will do the following:

- Stop autobuild
- Add any projects that are in the bnd workspace
  but not in the Eclipse workspace
- Delete any projects in the Eclipse workspace
  that are located in the bnd workspace but are no
  longer found
- Clean all projects the bnd way 
- Update _all_ the .classpath files
- Refresh the whole workspace
- Set the workspace build order to the bnd 
  build workspace build order
- Set concurrent build jobs to 10
- Do a clean build
- Restore autobuild

This fixes #4413

This patch also fixes  #4434. When compiler errors
are detected, the error is marked directly in the
Eclipse workspace. This used to be reported as an
error on the Project. There was a bug in generate
that did not clear the bnd errors and then this
caused the problem that some fixed errors were still
counted.

Signed-off-by: Peter Kriens <Peter.Kriens@aqute.biz>

2021-01-19 16:48 UTC, pkriens commented
Open issues I have is that I completely replace the .classpath file with a correct one:

- Is there a use case to have non-bnd info in the .classpath?
- Maybe this should be on a higher level that always automatically creates the .classpath?
-

2021-01-25 08:31 UTC, kriegfrj commented
Im sorry, i might not get to review this until next week.

2021-02-01 00:04 UTC, kriegfrj requested changes
> Open issues I have is that I completely replace the .classpath file with a correct one:
> 
> * Is there a use case to have non-bnd info in the .classpath?

In the past, I have run m2e and bndtools side-by-side in the same project so that I could use the maven cxf-codegen-plugin. I never quite got it working properly. But I think it would be a good idea for us to leave this option open. Our users might want to get creative!

> * Maybe this should be on a higher level that always automatically creates the .classpath?

I'm leaning towards this (I raised exactly that in my review). Using Eclipse APIs to manipulate .classpath (rather than manipulating it directly) future-proofs the implementation, and also means that Eclipse is aware of the changes and can update its in-memory models, trigger updates on any watchers, etc.

2021-02-01 00:19 UTC, kriegfrj commented on bndtools.builder/src/org/bndtools/builder/BndtoolsBuilder.java
> +						return dependsOn;
Actually, you could also change the last call to `report()` (L320) and get rid of `report()` too.

2021-02-08 14:59 UTC, gamerson commented on biz.aQute.bndlib/src/aQute/bnd/osgi/eclipse/EclipseUtil.java
> +public class EclipseUtil {
I agree that writing this file by hand may run into compatibility problems with other plugins or future versions of eclipse.

2021-02-08 15:04 UTC, gamerson commented on biz.aQute.bndlib/src/aQute/bnd/osgi/eclipse/EclipseUtil.java
> +public class EclipseUtil {
Agree, i think using Eclipse API for writing .classpath would be preferable.

2021-02-08 15:58 UTC, pkriens commented on biz.aQute.bndlib/src/aQute/bnd/osgi/eclipse/EclipseUtil.java
> +public class EclipseUtil {
Well, I'll take my chances. We are using a small subset and this file format has been stable for 20 years. We do regular updates so we find any issues quickly.

2021-03-30 15:36 UTC, merged