Slow IO
bndtools/bnd pull request #6023
Opened 2024-02-07 13:43 UTC by pkriens

- fixed the getBasedFile to not use canonical files since they were not needed
- Made classes for Windows and Other oses Fixes #6014

---
 Signed-off-by: Peter Kriens <Peter.Kriens@aQute.biz>

2024-02-07 16:53 UTC, jukzi commented on aQute.libg/src/aQute/lib/io/Other.java
> +			if (normalizedPath.getNameCount() > 0 && normalizedPath.getName(0)
index 0 only will not check against  something/../../escaped

2024-02-07 16:55 UTC, jukzi commented on aQute.libg/src/aQute/lib/io/Windows.java
> +				if (normalizedPath.startsWith(IO.DOTDOT)) {
that "startsWith" will not catch `something/../../escaped`

2024-02-07 16:56 UTC, jukzi requested changes
you are better off resolving relative against base an then check if its still legal

2024-02-08 10:38 UTC, pkriens commented
> you are better off resolving relative against base an then check if its still legal

I disagree. It is the responsibility of the caller to make sure the base is ok. Eclipse file systems and Java file systems and the OS file systems interact in horrible ways. See how hard the testing of this is, especially on windows.

The thing I learned here is that the `new File(base,path)` will ensure that any absolute file will **always** be a child of base. From the doc:

> If the {@code child} pathname string is absolute then it is converted into a **relative** pathname in a system-dependent way.

I.e. unless base is `null`, `new File(base,child)` will therefore always return a child of base.

2024-02-08 11:32 UTC, jukzi approved these changes
> I.e. unless base is `null`, `new File(base,child)` will therefore always return a child of base.

not really intuitive.
Thanks for caring about the issues. looks like the tests are sufficient

2024-02-08 13:14 UTC, pkriens commented
thanks for the collaboration

2024-02-08 13:14 UTC, merged