Implement new JDK21 SortedSet and List methods for SortedList
bndtools/bnd pull request #6134
Opened 2024-05-28 03:10 UTC by neeshy

As per #6131

2024-05-28 04:30 UTC, kriegfrj requested changes
Thanks for the update, @neeshy ! Looks like the compile fails because on Java 17 these methods do not exist. I think that we still need to preserve Java 17 compile compatibility. So perhaps a solution here will be to comment out the @Override line.

I suspect that this change will also require you to do a minor version update in `package-info.java` from 4.2.0 to 4.3.0:

https://github.com/bndtools/bnd/blob/master/aQute.libg/src/aQute/lib/collections/package-info.java

The build never got that far because of the compile error though.

2024-05-28 07:32 UTC, neeshy commented
I've removed the `@Override` lines and it seem to build fine without the version update in `package-info.java`.

2024-05-28 09:58 UTC, chrisrueger commented
> it seem to build fine without the version update in `package-info.java`.

Unfortunately not.
See failing build https://github.com/bndtools/bnd/actions/runs/9265278739/job/25492215091?pr=6134

2024-05-29 00:24 UTC, kriegfrj commented
Also, when you re-submit this fix, can you please massage your commit message to include "Fixes #6131" on the bottom line, so that the full message looks something like this:

```
[libg] Implement new JDK21 SortedSet and List methods for SortedList

Fixes #6131
```

That way we can use the commit history to refer back to all of this discussion for historical context if necessary, and as an added bonus when we merge it it will automatically close the associated issue. Adding the `[libg]` at the front, while not as important or enforced, is something that I have personally done in the past as it also allows us to see at a glance which part of the workspace the commit is for.

2024-05-29 01:12 UTC, neeshy commented
Ah, I was building it through my package manager which I can only assume suppresses that check. Pushed with the suggested changes.

2024-05-31 01:05 UTC, merged

2024-05-31 01:06 UTC, kriegfrj commented
Thank you so much, @neeshy ! Congratulations on earning your honorary "first contribution" badge!